package com.alperen.w_03.utils;

import android.content.Context;
import android.widget.EditText;

import androidx.appcompat.app.AlertDialog;

import com.alperen.w_03.R;
import com.alperen.w_03.model.CardModel;
import com.alperen.w_03.model.RecentTransactionsModel;
import com.alperen.w_03.model.UpcomingPaymentsModel;
import com.alperen.w_03.repository.locale.W03Dao;
import com.alperen.w_03.repository.locale.W03Database;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Created by Alperen on 24.08.2022.
 */
public class W03Util {
    public static void setEditTextError(String errorText, EditText editText) {
        editText.setError(errorText);
    }

    public static void createDialog(String title, String msg, Context context) {
        new AlertDialog.Builder(context)
                .setTitle(title)
                .setMessage(msg)
                .setPositiveButton("Okay", (dialogInterface, i) -> {
                })
                .show();
    }

    public static void fillDb(Context context) {
        W03Dao dao = W03Database.getInstance(context).w03Dao();

        // Generated by https://www.vccgenerator.org
        // Parameters:
        // Brand: Mastercard
        // Country: Turkey
        // Bank: T.C Ziraat Bankası A.S
        List<CardModel> cardList = new ArrayList<>();
        cardList.add(new CardModel("5136 6296 5795 4196", "Nicole Vosper"));
        cardList.add(new CardModel("5401 3054 9469 5791", "Anbar Fldes"));
        cardList.add(new CardModel("5118 8521 9812 8698", "Uzoamaka Kreijkes"));
        cardList.add(new CardModel("5282 0824 4673 4135", "Curtis Noguchi"));
        cardList.add(new CardModel("5136 6234 9582 5726", "Amelia Fiorentino"));

        List<RecentTransactionsModel> recentTransactions = new ArrayList<>();
        recentTransactions.add(new RecentTransactionsModel("Taxi Trip", "03 Aug 2022, 15:43", 56.50));
        recentTransactions.add(new RecentTransactionsModel("Laundry", "04 Aug 2022, 16:43", 22.75));
        recentTransactions.add(new RecentTransactionsModel("Grocery", "05 Aug 2022, 17:45", 45));
        recentTransactions.add(new RecentTransactionsModel("Electric Bill", "06 Aug 2022, 18:00", 1150.80));
        recentTransactions.add(new RecentTransactionsModel("Car Mechanic", "07 Sep 2022, 21:45", 16500.01));
        recentTransactions.add(new RecentTransactionsModel("Haircut", "12 Dec 2022, 15:15", 15));
        recentTransactions.add(new RecentTransactionsModel("House Clean", "15 Jan 2022, 13:26", 15));

        List<UpcomingPaymentsModel> upcomingPayments = new ArrayList<>();
        upcomingPayments.add(new UpcomingPaymentsModel("Freelance", "Unregular payment", 1500, "01/01/2000", "Nicole"));
        upcomingPayments.add(new UpcomingPaymentsModel("Mentorship", "Regular payment", 50, "15/03/2022", "Curtis"));
        upcomingPayments.add(new UpcomingPaymentsModel("Salary", "Regular payment", 7500, "25/03/2022", "Anbar"));
        upcomingPayments.add(new UpcomingPaymentsModel("Website Design", "One time payment", 750.25, "28/03/2022", "Amelia"));
        upcomingPayments.add(new UpcomingPaymentsModel("Alex's Debt", "Unregular payment", 1500, "29/03/2022", "Alex"));
        upcomingPayments.add(new UpcomingPaymentsModel("Local Guide", "Unregular payment", 100.25, "06/04/2022", "Uzoamaka"));

        cardList.forEach(dao::insertCards);
        upcomingPayments.forEach(dao::insertUpcomingPayments);
        recentTransactions.forEach(dao::insertRecentTransactions);
    }

    public static void cleanDb(Context context) {
        W03Dao dao = W03Database.getInstance(context).w03Dao();

        dao.deleteCards();
        dao.deleteUpcomingPayments();
        dao.deleteRecentTransactions();
    }
}
